version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install SSH client
          command: sudo apt-get update && sudo apt-get install -y openssh-client
      - run:
          name: Execute remote SSH command
          command: |
            sshpass -p "$SSH_PANERA_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_PANERA_USERNAME@$SSH_PANERA_HOST \
            "cd /home/paneramg/domains/mangazone.panera.mg/public_html && php artisan scraper:run --slug=dr-stone --stop-at=232"

workflows:
  version: 2
  dr_stone:
    triggers:
      - schedule:
          cron: "*/20 * * * *"
          filters:
            branches:
              only:
                - main
      - manual: {}
    jobs:
      - deploy
