version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: circleci/python:3.8

jobs:
  build:
    executor: ubuntu-executor
    steps:
      - checkout

  deploy:
    executor: ubuntu-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_PANERA_FINGERPRINT}"
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no $SSH_PANERA_USERNAME@$SSH_PANERA_HOST 'bash -s' < bash/deploy.sh

workflows:
  scheduled-deploy:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - deploy:
          requires:
            - build

  push-deploy:
    triggers:
      - push
    jobs:
      - build
      - deploy:
          requires:
            - build
    filters:
      branches:
        only:
          - main
