name: Jujutsu kaisen

on:
  # schedule:
  #   - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Connect and Scrape
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_PANERA_HOST }}
          username: ${{ secrets.SSH_PANERA_USERNAME }}
          password: ${{ secrets.SSH_PANERA_PASSWORD }}
          script: "cd /home/paneramg/domains/mangazone.panera.mg/public_html && php artisan scraper:run --slug=jujutsu-kaisen --stop-at=129"
